http_server:
  addr: "127.0.0.1"
  port: 9091
  write_timeout_ms: 100000
  read_timeout_ms: 100000
  # req_max_size is maximal size of request in bytes
  req_max_size: 16777216
  key_path: ""
  crt_path: ""

facedb:
  # facedb microservice address
  addr: "http://127.0.0.1:8080"
  # ...
  timeout_ms: 10000