http_server:
  # name is a name, which will be sent as server name to other microservices.
  name: "0.0.0.0:9000"
  # server_addr is IP:PORT or path to UNIX socket
  # on which server will listen.
  socket: "0.0.0.0:9000"
  # write_timeout is timeout for HTTP(S) write for addrs_in.
  write_timeout_ms: 100000
  # read_timeout is timeout for HTTP(S) read for addrs_in.
  read_timeout_ms: 100000
  # immed_resp specifies, if server should return answer only
  # after image processed (false) or immediately (true).
  immed_resp: true
  # key_path is path to TLS key (if empty, server will use HTTP).
  key_path: ""
  # crt_path is path to TLS cert (if empty, server will use HTTP).
  crt_path: ""

facedb:
  # facedb microservice address
  addr: "http://127.0.0.1:10000""